Fix compilation errors of IAccessibleTextSelectionContainer
LinuxA11y/IAccessible2 pull request #19
Opened 2022-03-06 00:28 UTC by michaelDCurran

## Issue
* The IAccessible2 IDL files could not be compiled due to a syntax error. 'bool' does not exist.
* IAccessibleTextSelectionContainer was missing from the resulting type library.

## Fix
* ia2TextSelection struct's startIsActive member used 'bool' as its data type. this does not exist in idl. This has been changed to 'boolean'. 
 * IAccessibleTextSelectionContainer has been declaired in the type library section, ensuring that this interface is included in the type library.

## Testing
Upgraded NVDA to include IAccessible2 with IAccessibleTextSelectionContainer. Ensured that IAccessibleTextSelectionContainer appeared in NVDA's COM interfaces.

Signed-off-by: Michael Curran <mick@nvaccess.org>

2022-03-06 13:52 UTC, OzancanKaratas commented
The description of pull request #17 is here:

> This deprecates the IAccessible2_3 interface.

Please delete the file.

2022-03-08 00:51 UTC, jcsteh requested changes

2022-03-08 00:51 UTC, jcsteh commented on api/IA2TypeLibrary.idl
> +	IAccessibleTextSelectionContainer;
I assume this is not meant to be in the diff?

2022-03-08 01:15 UTC, michaelDCurran commented on api/IA2TypeLibrary.idl
> +	IAccessibleTextSelectionContainer;
Not a mistake. IAccessibleTextSelectionContainer should be included in the type library. I forgot to do that in #17

2022-03-08 01:26 UTC, jcsteh commented on api/IA2TypeLibrary.idl
> +	IAccessibleTextSelectionContainer;
But it just says "IAccessibleTextSelectionContainer"; there's no "interface" statement?

2022-03-08 01:27 UTC, michaelDCurran commented on api/IA2TypeLibrary.idl
> +	IAccessibleTextSelectionContainer;
```suggestion
	interface IAccessibleTextSelectionContainer;
```

2022-03-08 01:29 UTC, michaelDCurran commented on api/IA2TypeLibrary.idl
> +	IAccessibleTextSelectionContainer;
Oh... right. It still compiled the type library fine. So I guess the keyword is not technically needed. However, I've added it in now. Yep, that was a mistake.

2022-03-31 03:21 UTC, closed without merging

2022-03-31 03:22 UTC, jcsteh commented
#20 included some other minor documentation and spacing fixes, so I merged that instead, but it is effectively the same.